//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientIWS.BikeAvailabilityEvent {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BikeAvailabilityEvent.ISubscriberService", CallbackContract=typeof(ClientIWS.BikeAvailabilityEvent.ISubscriberServiceCallback))]
    public interface ISubscriberService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubscriberService/Subscribe", ReplyAction="http://tempuri.org/ISubscriberService/SubscribeResponse")]
        void Subscribe(string city, string station, int refresh);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISubscriberService/Subscribe", ReplyAction="http://tempuri.org/ISubscriberService/SubscribeResponse")]
        System.Threading.Tasks.Task SubscribeAsync(string city, string station, int refresh);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubscriberServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/ISubscriberService/BikeAvailabilityUpdate")]
        void BikeAvailabilityUpdate(string city, string station, double nbAvailableBikes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISubscriberServiceChannel : ClientIWS.BikeAvailabilityEvent.ISubscriberService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubscriberServiceClient : System.ServiceModel.DuplexClientBase<ClientIWS.BikeAvailabilityEvent.ISubscriberService>, ClientIWS.BikeAvailabilityEvent.ISubscriberService {
        
        public SubscriberServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public SubscriberServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public SubscriberServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriberServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public SubscriberServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Subscribe(string city, string station, int refresh) {
            base.Channel.Subscribe(city, station, refresh);
        }
        
        public System.Threading.Tasks.Task SubscribeAsync(string city, string station, int refresh) {
            return base.Channel.SubscribeAsync(city, station, refresh);
        }
    }
}
